language: php
php:
  - 7.1
addons:
  postgresql: "9.6"
before_script:
  - composer install --no-interaction
  - psql -c "CREATE DATABASE teste;" -U postgres
  - cp .env.travis .env
  - php artisan migrate
script:
  - phpunit
