language: php
php:
  - 5.5
  - 7.0
  - 7.1

before_script:
  - composer install --no-interaction
  - psql -c "CREATE DATABASE teste;" -U postgres
  - cp .env.travis .env
  - php artisan migrate
script:
  - phpunit
